default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_DATABASE") { 'db' } %>
  username: <%= ENV.fetch("DB_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'postgres' } %>
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_DEVELOPMENT") { 'app_development' } %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_TEST") { 'app_test' } %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_PRODUCTION") { 'app_production' } %>